baseurl = "/"
languageCode = "en-us"
title = "Home"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/" #need to make a matching about
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "blog"
    url = "/categories/blog/"
    weight = 4
# Testing out whether I can direct items in the main menu to a specific category
[[menu.main]]
    name = "resources"
    url = "/categories/resources/"
    weight = 5
[[menu.main]]
    name = "guides"
    url = "/categories/guides/"
    weight = 6


#[[menu.feed]]
    #name = "Subscribe"
    #url = "/index.xml"

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "Open-Source | [Github](https://github.com/goodroot/hugo-classic) | [Keybase](https://keybase.io/goodroot)"
    custom_css = ["css/theme-override.css"]

# If you want to use Fathom (https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

