baseurl: /
languageCode: en-us
title: Classic
theme: hugo-classic
googleAnalytics: ''
ignoreFiles:
  - \.Rmd$
  - _files$
  - _cache$
enableEmoji: yes
footnotereturnlinkcontents: ↩
permalinks:
  post: /post/:year/:month/:day/:slug/
menu:
  feed:
    - name: Subscribe
      url: /index.xml
  main:
    - name: Categories
      url: /categories/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
params:
  custom_css: css/theme-override.css
  description: A simple, minimal blog for those who love text.
  fathomAnalytics:
    serverURL: analytics.example.com
    siteID: ABCDE
  footer: Open-Source | [Github](https://github.com/goodroot/hugo-classic) | [Keybase](https://keybase.io/goodroot)
