baseurl = "/"
languageCode = "en-us"
title = "Home"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

## Keeping these in here so that I can remember the structure
#[[menu.main]]
    #name = "Categories"
    #url = "/categories/"
    #weight = 2
#[[menu.main]]
    #name = "Tags"
    #url = "/tags/"
    #weight = 3
    
[[menu.main]]
    name = "guides"
    url = "/categories/guides/"
    weight = 4
[[menu.main]]
    name = "resources"
    url = "/categories/resources/"
    weight = 5 
[[menu.main]]
    name = "blog"
    url = "/categories/blog/"
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

#[[menu.feed]]
    #name = "Subscribe"
    #url = "/index.xml"

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "Open-Source | [Github](https://github.com/jacob-w-udell/unmaking-an-asset-class) | | [Source](https://github.com/goodroot/hugo-classic) | [Email](mailto:judell12@gmail.com)"
    custom_css = ["css/theme-override.css"]

# If you want to use Fathom (https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

